export const vaultIds = [
  16, //'PUNK'
  0, //'PUNK-BASIC'
  1, //'PUNK-ATTR-4'
  2, //'PUNK-ATTR-5'
  3, //'PUNK-ZOMBIE'
  15, //'PUNK-FEMALE'
  20, //'MASK'
  21, //'CUBES'
  18, //'VARIANT-DAVIS'
  22, //'BABES-BASIC'
  37, //'WAIFU'
  35, //'DUDE'
  29, //'TWERKYPEPE'
  // 41, //'BLOCKCITIES'
  40, //'BGANPUNK'
  49, // 'MOONCAT'
];
